<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>comment</key>
  <string>Soy Syntax</string>
  <key>fileTypes</key>
  <array>
    <string>soy</string>
  </array>
  <key>foldingStartMarker</key>
  <string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
  <key>foldingStopMarker</key>
  <string>^\s*\}</string>
  <key>keyEquivalent</key>
  <string>^~S</string>
  <key>name</key>
  <string>Soy</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>begin</key>
      <string>\{(literal)\}</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>declaration.tag.begin.soy.literal</string>
        </dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>tag.name.soy</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\{(/literal)\}</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>declaration.tag.end.soy.literal</string>
        </dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>tag.name.soy</string>
        </dict>
      </dict>
      <key>name</key>
      <string>text.soy.literal</string>
    </dict>

    <dict>
      <key>begin</key>
      <string>/\*\*(?!/)</string>
      <key>captures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.js</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\*/</string>
      <key>name</key>
      <string>comment.block.documentation.js</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.javaannotations</string>
        </dict>
      </array>
    </dict>

    <dict>
      <key>match</key>
      <string>\{(\$[a-zA-Z0-9_\-]+)\}</string>
      <key>name</key>
      <string>declaration.tag.soy.variable</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.soy</string>
        </dict>
      </dict>
    </dict>

    <dict>
      <key>match</key>
      <string>\{(/[a-zA-Z0-9_$\-]+)\}</string>
      <key>name</key>
      <string>declaration.tag.end.soy.any</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>tag.name.soy</string>
        </dict>
      </dict>
    </dict>

    <dict>
      <key>begin</key>
      <string>\{([a-zA-Z0-9]+)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>tag.name.soy</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>name</key>
      <string>declaration.tag.begin.soy.any</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\s+\.([a-zA-Z0-9_$\-]+)+</string>
          <key>name</key>
          <string>template.fullname.soy</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.template.name.soy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9_$\-]+)\s*=\s*([a-zA-Z0-9_$\-]+)</string>
          <key>name</key>
          <string>attribute.soy</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>attribute.name.soy</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>attribute.value.soy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9_$\-]+)\s*=\s*(\"[ a-zA-Z0-9_$\-]+\")</string>
          <key>name</key>
          <string>attribute.soy</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>attribute.name.soy</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>attribute.value.soy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9_$\-]+)\s*=\s*(\'[ a-zA-Z0-9_$\-]+\')</string>
          <key>name</key>
          <string>attribute.soy</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>attribute.name.soy</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>attribute.value.soy</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.soy</string>
</dict>
</plist>
